name: steam-house-booster

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: steam_booster
      POSTGRES_USER: steam_user
      POSTGRES_PASSWORD: steam_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - steam-network
    healthcheck:
      test: pg_isready -U steam_user -d steam_booster
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  server:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://steam_user:steam_password@postgres:5432/steam_booster
    volumes:
      - logs-volume:/app/logs
    networks:
      - steam-network
    ports:
      - "3000:3000"
    restart: unless-stopped

networks:
  steam-network:
    driver: bridge

volumes:
  postgres-data:
  logs-volume:
