version: '3.8'

name: steam-hour-booster

services:
  server:
    build: .
    container_name: steam-hour-booster
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://steam_user:steam_password@postgres:5432/steam_booster
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=steam_booster
      - DB_USER=steam_user
      - DB_PASSWORD=steam_password
    restart: "no"  # Temporarily disable restart to see the error
    volumes:
      - logs-volume:/app/logs
    networks:
      - steam-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    mem_limit: 1024m
    cpus: '1.0'

  postgres:
    image: postgres:latest
    container_name: steam-booster-postgres
    environment:
      POSTGRES_DB: steam_booster
      POSTGRES_USER: steam_user
      POSTGRES_PASSWORD: steam_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - steam-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U steam_user -d steam_booster"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "5432:5432"

networks:
  steam-network:
    driver: bridge

volumes:
  postgres-data:
  logs-volume:
